# Generated by Django 2.2.24 on 2021-06-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210627_1847'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['text'], name='posts_post_text_74d9a2_idx'),
        ),
    ]
